imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    read_from: %kernel.root_dir%/../www
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum: string
        options:
            1002: SET NAMES utf8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false

stof_doctrine_extensions:
    orm:
        default:
            tree: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

sonata_admin:
    title:      Говнокод.ru
    title_logo: /bundles/sonataadmin/logo_title.png
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            default:
                label: Базовые
                items: ~

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Govnokod\UserBundle\Entity\User

nelmio_solarium:
    endpoints:
        default:
            dsn: %solr_dsn%
            timeout: 10

    clients:
        default:
            endpoints: [ default ]

old_sound_rabbit_mq:
    connections:
        default:
            host:     %rabbitmq_host%
            port:     %rabbitmq_port%
            user:     %rabbitmq_user%
            password: %rabbitmq_password%
            vhost:    %rabbitmq_vhost%
            lazy:     true

    producers:
        index:
            connection: default
            exchange_options: {name: 'govnokod-index', type: direct}

    consumers:
        index:
            connection:       default
            exchange_options: {name: 'govnokod-index', type: direct}
            queue_options:    {name: 'govnokod-index'}
            callback:         app.message_consumer.index

hwi_oauth:
    firewall_name: main
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook_app_id%
            client_secret:       %facebook_app_secret%

        github:
            type:                github
            client_id:           %github_client_id%
            client_secret:       %github_client_secret%
            scope:               'user:email'

services:
    app.message_consumer.index:
        class: App\Consumer\Index
        arguments: [ @service_container ]