# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_index:
    pattern:  /
    defaults: { _controller: GovnokodPostsBundle:Posts:list }

govnokod_user:
    resource: "@GovnokodUserBundle/Resources/config/routing.yml"

govnokod_comments:
    resource: "@GovnokodCommentBundle/Resources/config/routing.yml"

govnokod_posts:
    resource: "@GovnokodPostsBundle/Resources/config/routing.yml"

govnokod_ratings:
    resource: "@GovnokodRatingsBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
