security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

            oauth:
                resource_owners:
                    facebook:           "/login/oauth-check/facebook"
                    github:             "/login/oauth-check/github"

                login_path:        /login
                failure_path:      /login/oauth

                oauth_user_provider:
                    service: govnokod.oauth.user_provider

            remember_me:
                key:      %secret%
                lifetime: 31536000 # 365 days in seconds
                #domain:   %cookie_domain%
            logout:       ~
            switch_user:  true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_MODERATOR ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
