rating_post_vote:
    pattern: /posts/{post_id}/vote/{rate}/
    defaults: { _controller: GovnokodRatingsBundle:Rate:postVote }
    requirements:
        post_id: \d+

rating_comment_vote:
    pattern: /comments/{comment_id}/vote/{rate}/
    defaults: { _controller: GovnokodRatingsBundle:Rate:commentVote }
    requirements:
        comment_id: \d+