parameters:
#    govnokod_code.example.class: Govnokod\PostsBundle\Example

services:
    sonata.admin.govnokod:
            class: Govnokod\PostsBundle\Admin\CodeCategoryAdmin
            arguments: [null, 'Govnokod\PostsBundle\Entity\Category', 'SonataAdminBundle:CRUD']
            tags:
                - { name: sonata.admin, manager_type: orm, label: Категории говнокода }
