fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

oauth_connect:
    pattern: /login/oauth
    defaults: { _controller: GovnokodUserBundle:OAuth:oauthLogin }

oauth_registration:
    pattern: /login/oauth/{key}
    defaults: { _controller: GovnokodUserBundle:OAuth:registration }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/oauth-check/facebook

github_login:
    pattern: /login/oauth-check/github